In [115]:
import numpy as np

In [116]:
N = 20
D = 5
Th = np.random.random((N, D))*2
x = np.random.random(D)

In [117]:
Th.dot(x)

array([ 2.9193502 ,  2.52983764,  2.16737747,  1.91744328,  1.11984621,
        1.74748488,  2.16101509,  3.28268068,  3.77020308,  1.50353467,
        2.7011824 ,  2.77747774,  2.03635698,  2.04673904,  2.62004906,
        2.10651332,  3.63638922,  0.67149849,  2.53211213,  2.2288366 ])

In [118]:
NB_CLASSES = 4
thresholds = [1, 3, 5]

In [119]:
thresholds = np.random.random(3)
thresholds

array([ 0.31822977,  0.19621616,  0.18573829])

In [120]:
np.exp(thresholds)

array([ 1.37469209,  1.2167899 ,  1.20410709])

In [121]:
np.exp(thresholds).dot(np.tri(3).T)

array([ 1.37469209,  2.59148199,  3.79558908])

In [122]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [123]:
cdf = sigmoid(Th.dot(x)[:, None] - thresholds)
cdf

array([[ 0.93093365,  0.93837801,  0.93898111],
       [ 0.90128707,  0.91162354,  0.91246407],
       [ 0.864027  ,  0.87773579,  0.87885579],
       [ 0.83190843,  0.84828683,  0.84963038],
       [ 0.69032015,  0.71578118,  0.71790795],
       [ 0.80678523,  0.8250969 ,  0.82660383],
       [ 0.86327779,  0.87705137,  0.87817676],
       [ 0.95094205,  0.95633095,  0.95676645],
       [ 0.96928993,  0.97272118,  0.97299783],
       [ 0.7659003 ,  0.7870641 ,  0.78881485],
       [ 0.91551809,  0.92448924,  0.92521744],
       [ 0.92123511,  0.92964583,  0.93032805],
       [ 0.84788745,  0.86296536,  0.86419973],
       [ 0.84922164,  0.86418848,  0.86541355],
       [ 0.9090276 ,  0.91862672,  0.91940653],
       [ 0.85671671,  0.87105253,  0.87222483],
       [ 0.96504656,  0.96893672,  0.96925055],
       [ 0.58741001,  0.61663325,  0.61910714],
       [ 0.90148924,  0.91180662,  0.91264557],
       [ 0.87108731,  0.8841797 ,  0.88524838]])

In [124]:
operator = np.fromfunction(lambda i, j: (j == i + 1) - 1 * (j == i), (3, 4), dtype=float)

In [125]:
np.fromfunction(lambda i, j: 1. * (j == 0), (1, NB_CLASSES), dtype=float)

array([[ 1.,  0.,  0.,  0.]])

In [126]:
operator

array([[-1,  1,  0,  0],
       [ 0, -1,  1,  0],
       [ 0,  0, -1,  1]])

In [127]:
pdf = cdf.dot(operator) + [1, 0, 0, 0]

In [128]:
import tensorflow as tf

In [129]:
sess = tf.InteractiveSession()
sess.run(tf.argmax(pdf, axis=1))

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [130]:
np.argmax(pdf, axis=1)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [131]:
np.argmax(pdf, axis=1)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [132]:
def logloss(x):
    return np.log(1 + np.exp(-x))

In [133]:
labels = np.round(np.random.random(N)*3)

In [134]:
labels

array([ 2.,  1.,  1.,  1.,  1.,  2.,  3.,  2.,  2.,  2.,  2.,  1.,  0.,
        3.,  1.,  2.,  2.,  1.,  2.,  1.])

In [135]:
sgn = np.fromfunction(lambda i, j: 2 * (1 + j < labels[i]) - 1, (N, L - 1), dtype=int)

In [136]:
delta = np.outer(Th.dot(x), np.ones(3)) - thresholds

In [137]:
logloss(sgn * delta).sum(axis=1)

array([ 5.65487554,  7.17739489,  6.20764354,  5.56366886,  3.69574892,
        3.71039728,  2.38339264,  6.32255626,  7.24467443,  3.3684874 ,
        5.26491588,  7.8594586 ,  5.86722618,  2.31494799,  7.42424508,
        4.26048122,  6.98919102,  2.80930126,  4.96971201,  6.36932063])

In [138]:
import tensorflow as tf

aa = tf.constant([1., 5., 3.])
a = tf.reshape(aa, (3, 1))
b = tf.ones([1, 3])

In [139]:
#sess = tf.InteractiveSession()
with tf.Session() as sess:
    print(sess.run(tf.matmul(a, b)))

[[ 1.  1.  1.]
 [ 5.  5.  5.]
 [ 3.  3.  3.]]


In [140]:
some_logits = Th.dot(x)
#thr = tf.cast(tf.constant(thresholds), tf.float64)
#lab = tf.constant(labels)

In [141]:
some_logits[:, None] - thresholds

array([[ 2.60112042,  2.72313403,  2.7336119 ],
       [ 2.21160787,  2.33362148,  2.34409935],
       [ 1.8491477 ,  1.97116131,  1.98163918],
       [ 1.59921351,  1.72122712,  1.73170499],
       [ 0.80161644,  0.92363005,  0.93410792],
       [ 1.42925511,  1.55126872,  1.56174659],
       [ 1.84278532,  1.96479893,  1.9752768 ],
       [ 2.96445091,  3.08646452,  3.09694239],
       [ 3.45197331,  3.57398692,  3.58446479],
       [ 1.1853049 ,  1.30731851,  1.31779638],
       [ 2.38295263,  2.50496624,  2.51544411],
       [ 2.45924797,  2.58126158,  2.59173945],
       [ 1.71812721,  1.84014082,  1.85061869],
       [ 1.72850927,  1.85052288,  1.86100075],
       [ 2.30181929,  2.4238329 ,  2.43431077],
       [ 1.78828355,  1.91029716,  1.92077503],
       [ 3.31815945,  3.44017305,  3.45065092],
       [ 0.35326872,  0.47528233,  0.4857602 ],
       [ 2.21388236,  2.33589597,  2.34637384],
       [ 1.91060683,  2.03262044,  2.04309831]])

In [147]:
2 * (range(4) - labels[:, None]) + 1

array([[-3., -1.,  1.,  3.],
       [-1.,  1.,  3.,  5.],
       [-1.,  1.,  3.,  5.],
       [-1.,  1.,  3.,  5.],
       [-1.,  1.,  3.,  5.],
       [-3., -1.,  1.,  3.],
       [-5., -3., -1.,  1.],
       [-3., -1.,  1.,  3.],
       [-3., -1.,  1.,  3.],
       [-3., -1.,  1.,  3.],
       [-3., -1.,  1.,  3.],
       [-1.,  1.,  3.,  5.],
       [ 1.,  3.,  5.,  7.],
       [-5., -3., -1.,  1.],
       [-1.,  1.,  3.,  5.],
       [-3., -1.,  1.,  3.],
       [-3., -1.,  1.,  3.],
       [-1.,  1.,  3.,  5.],
       [-3., -1.,  1.,  3.],
       [-1.,  1.,  3.,  5.]])

In [157]:
logits = tf.placeholder(tf.float32, shape=[None])
thr = tf.placeholder(tf.float32, shape=[None])
lab = tf.placeholder(tf.int32, shape=[None])

In [158]:
NB_CLASSES = 4

In [159]:
def tf_logloss(x):
    return tf.log(1 + tf.exp(-x))

In [172]:
def immediate_thresholds(labels, logits, thresholds):
    signs = tf.one_hot(labels, NB_CLASSES - 1) - tf.one_hot(labels - 1, NB_CLASSES - 1)
    delta = logits[:, None] - thresholds
    return tf.reduce_sum(tf_logloss(signs * delta), axis=1)

In [177]:
signs = tf.one_hot(labels, NB_CLASSES - 1) - tf.one_hot(labels - 1, NB_CLASSES - 1)

In [178]:
signs = tf.sign(2 * (tf.range(NB_CLASSES, dtype=tf.float32) - labels[:, None]) + 1)

In [164]:
def all_thresholds(labels, logits, thresholds):
    #batch_size = tf.size(labels).eval()
    #sgn = np.fromfunction(lambda i, j: 2 * (1 + j < labels.eval()[i]) - 1, (batch_size, NB_CLASSES - 1), dtype=int)
    signs = tf.sign(2 * (tf.range(NB_CLASSES, dtype=tf.float32) - labels[:, None]) + 1)
    delta = logits[:, None] - thresholds
    return tf.reduce_sum(tf_logloss(signs * delta), axis=1)

In [166]:
metrics = immediate_thresholds(lab, logits, thr)

In [127]:
np.random.random((5))[None, :].shape

(1, 5)

In [132]:
delta = logits[:, None] - thr

In [179]:
with tf.Session() as sess:
    print(sess.run(signs, feed_dict={lab: labels, logits: some_logits, thr: thresholds}))

[[-1. -1.  1.  1.]
 [-1.  1.  1.  1.]
 [-1.  1.  1.  1.]
 [-1.  1.  1.  1.]
 [-1.  1.  1.  1.]
 [-1. -1.  1.  1.]
 [-1. -1. -1.  1.]
 [-1. -1.  1.  1.]
 [-1. -1.  1.  1.]
 [-1. -1.  1.  1.]
 [-1. -1.  1.  1.]
 [-1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [-1. -1. -1.  1.]
 [-1.  1.  1.  1.]
 [-1. -1.  1.  1.]
 [-1. -1.  1.  1.]
 [-1.  1.  1.  1.]
 [-1. -1.  1.  1.]
 [-1.  1.  1.  1.]]


In [176]:
labels

array([ 2.,  1.,  1.,  1.,  1.,  2.,  3.,  2.,  2.,  2.,  2.,  1.,  0.,
        3.,  1.,  2.,  2.,  1.,  2.,  1.])

In [39]:
result = all_thresholds(logits, thr, lab)

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [46]:
with tf.Session() as sess:
    print(sess.run(all_thresholds(lab, logits, thr), feed_dict={lab: labels, logits: Th.dot(x), thr: thresholds}))

[ 1.6303095   1.20975196  1.60408551  1.75802107  1.24029919  1.88728056
  0.76261534  2.5268018   1.38458055  2.42626421  3.34016564  1.92546685
  0.98619173  4.00346476  2.00474428  1.57902     2.66738516  1.99304748
  3.28847223  1.96645723]
